/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthShell: typeof import('./src/components/auth/AuthShell.vue')['default']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    LiveSidePanel: typeof import('./src/components/live/LiveSidePanel.vue')['default']
    MediaTile: typeof import('./src/components/media/MediaTile.vue')['default']
    PageHeader: typeof import('./src/components/layout/PageHeader.vue')['default']
    RoomControlBar: typeof import('./src/components/room/RoomControlBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./src/components/ui/StatusTag.vue')['default']
    SummaryCard: typeof import('./src/components/ui/SummaryCard.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCard: typeof import('vant/es')['Card']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VenueSwitcher: typeof import('./src/components/live/VenueSwitcher.vue')['default']
    VideoPlayer: typeof import('./src/components/media/VideoPlayer.vue')['default']
    VotePanel: typeof import('./src/components/meeting/VotePanel.vue')['default']
  }
}
